spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:hojuMoney
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://refactoring-hojumoney.store/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://refactoring-hojumoney.store/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope:
              - email
              - profile_image
              - name
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://refactoring-hojumoney.store/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope:
              - account_email
              - profile_image
              - profile_nickname
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  main:
    allow-circular-references: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
    context-path: /
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: j12323qwer1213ffsafsfsadf12dsddqwf
  access-token-expiration-minutes: 10080
  refresh-token-expiration-minutes: 10080